[package]
name = "cqpsdk"
version = "0.0.1"
authors = [ "evshiron", "doylecnn" ]

[dependencies]
encoding = "0.2"
byteorder="1"
base64 = "~0.6.0"
serde="1.0"
serde_derive ="1.0"

[lib]
name = "cqpsdk"
crate-type = [ "rlib" ]